(******************************************************************************)
(*  Act.v                                                                     *)
(*                                                                            *)
(*  The acts of government the Constitution regulates.  Each constructor      *)
(*  records the facts a clause needs to decide whether the act complies.      *)
(*  A World lists the acts that occurred; each clause is a condition on the   *)
(*  acts of its kind.  Laws (Measure) are checked through their fields.       *)
(******************************************************************************)

From CV Require Import Types.

Inductive Act : Type :=
  (* ---- Lawmaking, votes and the internal order of each House (Art. I, ss. 5-7) ---- *)
  | EnactLaw (m : Measure)
  | ResolveAct (m : Measure)
  | RollCall (ch : Chamber) (v : Vote)
  | Expel (ch : Chamber) (v : Vote)
  | Adjourn (ch : Chamber) (days : nat) (other_house_consents : bool) (same_place : bool)
  | SeatMember (ch : Chamber) (judged_by_own_house : bool)
  | MemberArrest (charge : ArrestCharge) (during_attendance : bool)
  | MemberSpeech (questioned_in_other_place : bool)
  | MemberPay (set_by_law : bool) (paid_from_treasury : bool)
  | OfficeGrant (appointed_member : bool) (office_created_or_emolument_raised : bool)
  | DualOffice (member : bool) (federal_officer : bool)
  | ElectionRules (by_state_legislature : bool) (by_congress : bool) (senate_places : bool)
  (* ---- Vacancies and impeachment (Art. I, ss. 2-3) ---- *)
  | FillVacancy (ch : Chamber) (method : FillMethod)
  | ImpeachBy (ch : Chamber)
  | SenateTie (vice_president_voted : bool) (yeas : nat) (nays : nat)
  | SenateConviction (oath : bool) (president_tried : bool) (chief_justice_presides : bool) (v : Vote)
  | ImpeachmentJudgment (removal : bool) (disqualification : bool) (other_penalty : bool)
      (later_prosecution_barred : bool)
  (* ---- Powers of Congress and the limits on Congress and the States (Art. I, ss. 8-10) ---- *)
  | Borrow (on_credit_of_us : bool)
  | DeclareWar (by_congress : bool)
  | MilitiaCall (purpose : MilitiaPurpose)
  | MilitiaOrganization (officers_appointed_by_states : bool) (training_by_congress_discipline : bool)
  | DistrictLegislation (kind : ExclusiveKind) (area_sq_miles : nat) (ceded_and_accepted : bool)
      (state_consent : bool)
  | ImportationBan (year : nat)
  | ImportationTax (year : nat) (dollars : nat)
  | SuspendHabeas (cause : HabeasCause) (public_safety_requires : bool)
  | DirectTax (apportioned : bool)
  | IncomeTax (on_incomes : bool)
  | ExportTax (on_exports : bool)
  | PortRegulation (preference : bool) (vessels_obliged : bool)
  | Draw (amount : nat) (appropriated_by_law : bool)
  | TitleGrant (by_united_states : bool)
  | ForeignPresent (office_holder : bool) (congress_consent : bool)
  | StateBan (kind : StateBanKind)
  | StateDuty (consent : bool) (inspection_absolutely_necessary : bool)
      (net_to_treasury : bool) (revisable_by_congress : bool)
  | StateTonnage (consent : bool)
  | StatePeaceForces (consent : bool)
  | StateCompact (consent : bool)
  | StateWar (invaded_or_imminent_danger : bool)
  (* ---- Executive and electoral acts (Art. II) ---- *)
  | ElectorAppointment (state : USState) (electors : nat) (disqualified : bool)
  | PresidentDecision (total_electors top_votes : nat) (house_chose : bool)
      (candidates_considered : nat) (states_quorum : bool) (states_majority : bool)
  | VPDecision (total_electors top_votes : nat) (senate_chose : bool)
      (candidates_considered : nat) (senate_quorum : bool) (senate_majority : bool)
  | CandidateRegistration (p : Person)
  | VPCandidacy (p : Person)
  | Succession (trigger : SuccessionTrigger) (successor : SuccessorKind) (vp_vacant : bool)
  | PresidentPay (during_term : bool) (changed : bool)
  | ForeignEmolument (from_united_states_or_state : bool)
  | ExecutiveAct (sworn : bool) (faithful_to_laws : bool)
  | MilitiaCommand (in_actual_service : bool)
  | OpinionRequest (principal_officer : bool)
  | Pardon (impeachment_case : bool)
  | TreatyRatify (v : Vote)
  | Appointment (established_by_law : bool) (confirmed : bool) (inferior : bool)
      (vested : option VestTarget)
  | RecessCommission (during_recess : bool) (expires_end_of_next_session : bool)
  | ConveneHouses (extraordinary : bool)
  | AdjournHouses (disagreement_on_time : bool)
  | ReceiveEnvoy (accepted : bool)
  | CommissionOfficer (appointed_and_confirmed : bool)
  | RemovalOnImpeachment (impeachment_conviction : bool) (ground : RemovalGround)
  (* ---- Judiciary (Art. III) ---- *)
  | JudgeRemoval (impeachment_conviction : bool)
  | JudgeCompensation (diminished : bool)
  | CourtCase (category : CaseCategory) (forum : Forum)
  | CriminalTrial (jury : bool) (crime_state : option USState) (trial_state : USState)
      (place_by_law : bool) (impeachment : bool)
  | TreasonCharge (levied_war : bool) (adhered_with_aid : bool)
  | TreasonConviction (two_witnesses_same_overt_act : bool) (confession_open_court : bool)
  | TreasonPunishment (declared_by_congress : bool) (corruption_of_blood : bool)
      (forfeiture_beyond_life : bool)
  (* ---- Relations among the States (Art. IV) ---- *)
  | RecordRecognition (refused : bool)
  | CitizenPrivilege (discriminates_against_out_of_state : bool)
  | Extradition (demand_proper : bool) (refused : bool)
  | FormState (admitted_by_congress : bool) (within_other_state : bool) (merger : bool)
      (legislatures_consent : bool) (congress_consent : bool)
  | TerritoryDisposal (by_congress : bool)
  | StateGovernment (republican : bool)
  | InvasionProtection (state_invaded : bool) (protected : bool)
  | DomesticViolenceAid (applied_by_legislature : bool) (applied_by_executive : bool)
      (legislature_cannot_convene : bool) (granted : bool)
  (* ---- Amendment procedure (Art. V) ---- *)
  | ProposeByCongress (num : nat) (house : Vote) (senate : Vote)
  | CallConvention (num : nat) (applications : nat)
  | RatifyAmendment (num : nat) (states : nat) (mode : RatifyMode) (years_after_submission : nat)
  | EarlyAmendment (num : nat) (year : nat) (touches_9_1_or_9_4 : bool)
  | SenateSuffrageChange (num : nat) (state : USState) (deprived : bool) (consent : bool)
  (* ---- Supremacy and oaths (Art. VI) ---- *)
  | DebtAct (pre_adoption : bool) (repudiated : bool)
  | StateLawEnforced (conflicts_with_federal : bool)
  | OfficerEntry (kind : OfficeKind) (oath_taken : bool) (religious_test : bool)
  (* ---- Bill of Rights (Amendments I-X) ---- *)
  | ArmsRestriction (infringes : bool)
  | Quartering (in_peace : bool) (owner_consent : bool) (in_war : bool) (by_law : bool)
  | Search (reasonable : bool)
  | WarrantIssued (probable_cause : bool) (oath_or_affirmation : bool) (particular : bool)
  | CapitalCharge (grand_jury_indictment : bool) (military_exception : bool)
      (capital_or_infamous : bool)
  | Prosecution (double_jeopardy : bool)
  | CompelledTestimony (criminal_case : bool) (compelled : bool)
  | Deprivation (due_process : bool)
  | Taking (for_public_use : bool) (just_compensation : bool)
  | CriminalProsecution (speedy public impartial_jury district_by_law informed confronted
      compulsory_process counsel : bool)
  | CivilSuit (amount : nat) (jury_preserved : bool) (reexamined_otherwise : bool)
  | Sanction (kind : SanctionKind) (excessive_or_cruel : bool)
  | DenialByEnumeration (denies_retained_right : bool)
  (* ---- Amendments XI-XXVII ---- *)
  | SuitAgainstState (other_state_or_foreign_plaintiff : bool)
  | ServitudeAct (involuntary : bool) (punishment_after_conviction : bool)
  | EnforcementLaw (amendment : nat)
  | Citizenship (born_or_naturalized : bool) (subject_to_jurisdiction : bool)
      (us_citizen : bool) (state_citizen : bool)
  | StateAbridges (state : USState) (privileges_abridged : bool)
  | StateDeprivation (state : USState) (due_process : bool)
  | EqualProtectionDenial (state : USState) (denied : bool)
  | SuffrageDenial (state : USState) (denied_male : nat) (male_21 : nat)
      (basis_before : nat) (basis_after : nat) (excepted : bool)
  | Disqualified (office : OfficeKind) (prior_oath : bool) (insurrection_or_aid : bool)
      (two_thirds_each_house_removed : bool)
  | PublicDebt (authorized_by_law : bool) (questioned : bool)
  | RebellionClaim (kind : RebellionClaimKind) (paid_or_assumed : bool)
  | VoteDenialRace (denied : bool) (on_race_color_or_servitude : bool)
  | SenatorElection (chosen_by_people : bool) (term_years : nat)
      (electors_as_most_numerous : bool)
  | VoteDenialSex (denied : bool) (on_sex : bool)
  | InauguralSuccession (president_elect_died : bool) (vp_elect_became_president : bool)
      (not_qualified : bool) (vp_elect_acts : bool)
  | ChoiceDeathLaw (provided_by_law : bool)
  | TransportLiquor (into_state : bool) (violates_state_law : bool)
      (for_delivery_or_use : bool)
  | DCElectors (count : nat)
  | PollTaxDenial (federal_election : bool) (for_nonpayment : bool) (denied : bool)
  | VPNomination (confirmed_by_both_houses : bool)
  | PresidentDeclaration (written_and_transmitted : bool) (declares_inability : bool)
      (vp_acts : bool)
  | CabinetDeclaration (vp_and_majority_declare : bool) (transmitted : bool)
      (vp_acts_immediately : bool)
  | PresidentContest (within_four_days : bool) (congress_days : nat)
      (two_thirds_both : bool) (vp_continues : bool)
  | VoteDenialAge (age : nat) (denied : bool)
  | PayChange (election_intervened : bool) (in_force : bool).
